// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    InputBox: typeof import('./components/InputBox.vue')['default']
    README: typeof import('./components/README.md')['default']
    Settings: typeof import('./components/Settings.vue')['default']
  }
}

export { }
