// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BannerLogo: typeof import('./components/BannerLogo.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    InputBox: typeof import('./components/InputBox.vue')['default']
    IRiInformationLine: typeof import('~icons/ri/information-line')['default']
    IRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IRiSearchLine: typeof import('~icons/ri/search-line')['default']
    IRiSettings2Line: typeof import('~icons/ri/settings2-line')['default']
    IRiSunLine: typeof import('~icons/ri/sun-line')['default']
    IRiTranslate: typeof import('~icons/ri/translate')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    README: typeof import('./components/README.md')['default']
    Settings: typeof import('./components/Settings.vue')['default']
  }
}

export { }
