// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    ICarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    InputBox: typeof import('./components/InputBox.vue')['default']
    IRiCloudLine: typeof import('~icons/ri/cloud-line')['default']
    IRiGithubLine: typeof import('~icons/ri/github-line')['default']
    IRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IRiSearchLine: typeof import('~icons/ri/search-line')['default']
    IRiSunLine: typeof import('~icons/ri/sun-line')['default']
    IRiTranslate: typeof import('~icons/ri/translate')['default']
    README: typeof import('./components/README.md')['default']
    Settings: typeof import('./components/Settings.vue')['default']
  }
}

export { }
